// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndoegsjukgxjjiwykgus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kb2Vnc2p1a2d4amppd3lrZ3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzU4MjYsImV4cCI6MjA3MjYxMTgyNn0.XsFA6Gcw1mHBlFv-VW7PBK91Hr3CZGjxNQxzkPVN2ZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});